file: populate.o check.o inc_nsets.o main.o
	gcc -Wall populate.o check.o inc_nsets.o main.o -o file

populate.o: populate.c
	gcc -Wall -c populate.c -o populate.o
	
check.o: check.c
	gcc -Wall -c check.c -o check.o
	
inc_nsets.o: inc_nsets.c
	gcc -Wall -c inc_nsets.c -o inc_nsets.o

main.o: main.c
	gcc -Wall -c main.c -o main.o
