file: find_word.o find_all_words.o main.o
	gcc -Wall find_word.o find_all_words.o main.o -o file

find_word.o: find_word.c
	gcc -Wall -c find_word.c -o find_word.o
	
find_all_words.o: find_all_words.c
	gcc -Wall -c find_all_words.c -o find_all_words.o

main.o: main.c
	gcc -Wall -c main.c -o main.o
